<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        // param callback
        const get = (url) => {

            return new Promise((resolve,reject)=>{
                const xhr = new window.XMLHttpRequest()
    
                xhr.onreadystatechange = () => {
                    if(xhr.readyState === 4)
                    {
                        if(xhr.status === 200)
                        {
                            // console.log('terminé')
                            resolve(xhr.responseText)
                        }else{
                            reject(xhr)
                        }
                    }
                }
                xhr.open('GET',url,true)
                xhr.send()
            })
        }

        // get('https://jsonplaceholder.typicode.com/users').then((response)=>{
        //     console.log(response)
        // }).catch((error)=>{
        //     console.log(error)
        // })

        // get renvoie tjrs une promesse (then / catch)
        // si erreur, le then n'est pas effectué, il va chercher le prochain catch qu'il va voir
        const getPosts = () => {
            return get('https://jsonplaceholder.typicode.com/users').then((response)=>{
                const users = JSON.parse(response)
                return get('https://jsonplaceholder.typicode.com/comments?userId='+users[0].id)
            }).then((response)=>{
                const posts = JSON.parse(response)
                return posts
            })
        }

        // getPosts().then((posts)=>{
        //     console.log(posts[0])
        // }).catch((error)=>{
        //     console.log(error)
        // })

        // on peut continuer à faire des then même après une erreur (catch) car cela renvoie une promesse également

        getPosts().then((posts)=>{
            console.log(posts[0])
        }).catch((error)=>{
            console.log(error)
        }).then(()=>{
            console.log('fin des requêtes AJAX')
        })
    
        /* https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Promise */

    
    </script>


</body>
</html>